# Generated by Django 5.0.14 on 2026-02-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='category',
            field=models.CharField(choices=[('institution', 'Institution'), ('nature', 'Nature'), ('business', 'Business'), ('government', 'Government'), ('transport', 'Transport'), ('landmark', 'Landmark'), ('city', 'City'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
