# Generated by Django 5.0.14 on 2026-02-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_waypoint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='altitude',
            field=models.FloatField(default=0.0, help_text='Altitude in meters above sea level'),
        ),
    ]
